site_name: Iterable Linq Utility
repo_url: https://github.com/Amebus/iterable-linq-utility
repo_name: amebus/iterable-linq-utility
theme:
  icon:
    repo: simple/github
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.tabs.link
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: ⚓︎
  - tables
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css

nav:
  - Overview: 
    - index.md
    - Getting Started: getting-started.md
    - Basic Concepts: basic-concepts.md
    - Alternative Projects: alternative-projects.md
    - How to contribute: how-to-contribute.md
  - Advanced Concepts: 
    - advanced-concepts/index.md
    - Interoperability with other libraries: advanced-concepts\interoperability-with-other-libraries.md
  - Api Reference:
    - api-reference/index.md
    - Actions: api-reference/actions.md
    - Transformations: api-reference/transformations.md
  - Glossary: glossary.md