name: Npm Publish

on:
  release:
    types: [created]

jobs:
  publish-package:
      needs: build
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 22
            registry-url: https://registry.npmjs.org/
        - run: pnpm install
        - run: pnpm run build
        - run: pnpm run test
        - run: npm publish
          env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy-doc:
    needs: publish-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - name: Deploy doc
        working-directory: ./documentation
        run: mkdocs gh-deploy --force
